name: Move a task to a different section

on:
  pull_request:
    types: [opened]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: everphone-gmbh/github-asana-action@385529c
        continue-on-error: true
        with:
          asana-pat: ${{ secrets.ASANA_SECRET }}
          action: 'move-section'
          targets: '[{"project": "github連携テスト", "section": "REVIEW"}]'