on: [push]

jobs:
  hello-world:
    runs-on: ubuntu-latest
    name: Greeting
    steps:
      - name: Hello
        uses: mackey55555/github-asana-plugin@v1.0.1
        with:
          asana-secret: ${{ secrets.ASANA_SECRET }}